name: create release on new tags

on:
  push:
    # Publish semver tags as releases.
    tags: '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-and-push:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Print tag to GITHUB_OUTPUT
        id: get_tag
        run: |
          echo "release_version=${GITHUB_REF#refs/*/}" | tee -a $GITHUB_OUTPUT

      # Todo: check that the tag == chart-verifier version ?
      # Would prevent falty tags to be pushed
      - name: Build binary and make tarball
        id: build_bin
        run: |
          make bin
          TARBALL_NAME="my-chart-verifier.tgz-${{ steps.get_tag.outputs.release_version }}.tgz"
          tar -zcvf $TARBALL_NAME -C out/ my-chart-verifier
          export TARBALL_PATH=$(realpath $TARBALL_NAME)
          echo "tarball_path=$TARBALL_PATH" | tee -a $GITHUB_OUTPUT

      - name: Check that the tag matches the current version
        id: check_tag_and_version
        run: |
          release_version=${{ steps.get_tag.outputs.release_version }}
          bin_version=$(out/my-chart-verifier version --as-data | jq -r .version)
          if [[ "$release_version" != "$bin_version" ]]; then
            echo "Binary version ($bin_version) doesn't match tag ($release_version)" && exit 1
          fi

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Set up Python scripts
        run: |
          # set up python requirements and scripts on PR branch
          python3 -m venv ve1
          cd scripts && ../ve1/bin/pip3 install -r requirements.txt && cd ..
          cd scripts && ../ve1/bin/python3 setup.py install && cd ..

      - name: Generate release body
        id: release_body
        run: ve1/bin/print-release-body

      - name: Create the the release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.get_tag.outputs.release_version }}
          body: ${{ steps.release_body.outputs.PR_release_body }}
          files: ${{ steps.build_bin.outputs.tarball_path }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

